# Generated by Django 5.0.2 on 2024-02-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capp', '0003_course_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='STAFF',
        ),
    ]
